ci/cd test 1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,9 +23,10 @@ jobs:
                     echo "🔄 Sourcing nvm..."
                     export NVM_DIR="\$HOME/.nvm"
                     [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
-
+                    
                     echo "📦 Using default Node..."
                     nvm use node
+                    echo "Node: \$(node -v || echo '❌ Not Found')"
 
                     echo "🧪 Checking Node and NPM..."
                     echo "Node: \$(node -v || echo '❌ Not Found')"
